import type { Collection } from "tinacms";

const pageUi = {
  allowedActions: {
    create: false,
    delete: false,
  },
} as const;

const pagesPath = "content/pages";
const jsonFormat = "json" as const;

/** Tina list editor: show title / name / label / question / image alts instead of "Item 1". */
const listItemUi = {
  itemProps: (item: Record<string, unknown>) => {
    const title = item?.title;
    const name = item?.name;
    const label = item?.label;
    const question = item?.question;
    const beforeAlt = item?.beforeAlt;
    const afterAlt = item?.afterAlt;
    const value = item?.value;
    const subtitle = item?.subtitle;
    let questionPreview = "";
    if (typeof question === "string" && question.trim()) {
      const t = question.trim();
      questionPreview = t.length > 60 ? `${t.slice(0, 60)}…` : t;
    }
    return {
      label:
        (typeof title === "string" && title.trim()) ||
        (typeof name === "string" && name.trim()) ||
        (typeof label === "string" && label.trim()) ||
        questionPreview ||
        (typeof beforeAlt === "string" && beforeAlt.trim()) ||
        (typeof afterAlt === "string" && afterAlt.trim()) ||
        (typeof subtitle === "string" && subtitle.trim()) ||
        (typeof value === "string" && value.trim()) ||
        "Item",
    };
  },
} as const;

export const pageCollections: Collection[] = [
  {
    name: "home",
    label: "Home page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "home" },
    ui: pageUi,
    fields: [
      { type: "string", name: "heroKicker", label: "Hero small line (above the headline)" },
      { type: "string", name: "heroTitle", label: "Hero headline" },
      { type: "string", name: "heroTitleAccent", label: "Hero headline, last words (in blue)" },
      { type: "string", name: "heroSubtitle", label: "Hero text (keep under 20 words)", ui: { component: "textarea" } },
      { type: "image", name: "heroImage", label: "Hero photo" },
      { type: "string", name: "heroImageAlt", label: "Hero photo description (for screen readers)" },
      { type: "string", name: "primaryCtaLabel", label: "Main button label" },
      { type: "string", name: "secondaryCtaLabel", label: "Second button label" },
      {
        type: "object",
        name: "facts",
        label: "Facts strip (4 items)",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "value", label: "Number", required: true },
          { type: "string", name: "unit", label: "Unit (mm, h, or leave empty)" },
          { type: "string", name: "label", label: "Text under the number" },
        ],
      },
      { type: "string", name: "buildHeading", label: "What I build: heading" },
      { type: "string", name: "buildIntro", label: "What I build: intro", ui: { component: "textarea" } },
      {
        type: "object",
        name: "services",
        label: "What I build: 3 tiles (first one is the big one)",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Title", required: true },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          { type: "image", name: "image", label: "Photo" },
          { type: "string", name: "imageAlt", label: "Photo description" },
          { type: "string", name: "link", label: "Opens (optional)", description: "A service page, e.g. /services/fitted-wardrobes" },
        ],
      },
      { type: "string", name: "processHeading", label: "Process: heading" },
      { type: "image", name: "processImage", label: "Process: drawing (transparent PNG)" },
      { type: "string", name: "processImageAlt", label: "Process: drawing description" },
      { type: "string", name: "processCaption", label: "Process: caption under the drawing" },
      {
        type: "object",
        name: "steps",
        label: "Process: steps",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Step name", required: true },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
        ],
      },
      { type: "string", name: "processLinkLabel", label: "Process: link label" },
      { type: "string", name: "appKicker", label: "CabinetOS: small line" },
      { type: "string", name: "appHeading", label: "CabinetOS: heading" },
      { type: "string", name: "appBody", label: "CabinetOS: text", ui: { component: "textarea" } },
      { type: "image", name: "appImage", label: "CabinetOS: screenshot" },
      { type: "string", name: "appImageAlt", label: "CabinetOS: screenshot description" },
      { type: "string", name: "appLinkLabel", label: "CabinetOS: link label" },
      { type: "string", name: "blogHeading", label: "Blog: heading (shows the 3 newest posts)" },
      { type: "string", name: "quoteHeading", label: "Quote: heading" },
      { type: "string", name: "quoteBody", label: "Quote: text", ui: { component: "textarea" } },
      { type: "string", name: "phone", label: "Phone number" },
      { type: "string", name: "email", label: "Email address" },
      { type: "string", name: "quotePanelHeading", label: "Quote box: heading" },
      { type: "string", name: "quotePanelBody", label: "Quote box: text", ui: { component: "textarea" } },
      { type: "string", name: "quoteNextSteps", label: "Quote box: what happens next", list: true },
      { type: "string", name: "quoteNote", label: "Quote box: small note under the button" },
    ],
  },
  {
    name: "about",
    label: "About page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "about" },
    ui: pageUi,
    fields: [
      { type: "string", name: "title", label: "Title", isTitle: true, required: true },
      { type: "string", name: "titleAccent", label: "Title accent" },
      { type: "string", name: "storyParagraphs", label: "Story paragraphs", list: true, ui: { component: "textarea" } },
      { type: "string", name: "storyClosingLead", label: "Closing paragraph (before bold)" },
      { type: "string", name: "storyClosingBold", label: "Closing bold word" },
      { type: "string", name: "storyClosingRest", label: "Closing paragraph (after bold)", ui: { component: "textarea" } },
      {
        type: "object",
        name: "stats",
        label: "Stats",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "label", label: "Label" },
          { type: "string", name: "value", label: "Value" },
        ],
      },
      {
        type: "object",
        name: "differentiators",
        label: "Differentiators",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Title" },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
        ],
      },
      {
        type: "object",
        name: "socialLinks",
        label: "Social links",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "label", label: "Label" },
          { type: "string", name: "url", label: "URL" },
        ],
      },
      { type: "image", name: "profileImage", label: "Profile image" },
      {
        type: "string",
        name: "profileImageStyle",
        label: "Profile image style",
        options: [
          { value: "rounded", label: "Rounded" },
          { value: "circle", label: "Circle" },
          { value: "square", label: "Square" },
          { value: "phone-frame", label: "Phone frame" },
        ],
      },
      { type: "string", name: "photoPlaceholderEmoji", label: "Photo placeholder emoji" },
      { type: "string", name: "photoPlaceholderText", label: "Photo placeholder text" },
    ],
  },
  {
    name: "contact_page",
    label: "Contact page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "contact" },
    ui: pageUi,
    fields: [
      { type: "string", name: "title", label: "Title", isTitle: true, required: true },
      { type: "string", name: "titleAccent", label: "Title accent" },
      { type: "string", name: "subtitle", label: "Subtitle", ui: { component: "textarea" } },
      { type: "string", name: "email", label: "Email" },
      { type: "string", name: "phone", label: "Phone" },
      { type: "string", name: "address", label: "Address" },
      { type: "string", name: "responseTimeLabel", label: "Response time label" },
      { type: "string", name: "responseTimeValue", label: "Response time value" },
      { type: "boolean", name: "formEnabled", label: "Form enabled" },
      { type: "string", name: "formHeading", label: "Form heading" },
      { type: "string", name: "formSubmitLabel", label: "Submit button label" },
    ],
  },
  {
    name: "portfolio_page",
    label: "Portfolio page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "portfolio" },
    ui: pageUi,
    fields: [
      { type: "string", name: "title", label: "Title", isTitle: true, required: true },
      { type: "string", name: "titleAccent", label: "Title accent" },
      { type: "string", name: "subtitle", label: "Subtitle", ui: { component: "textarea" } },
      { type: "string", name: "categories", label: "Categories", list: true },
      {
        type: "object",
        name: "projects",
        label: "Projects",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Title", required: true },
          { type: "image", name: "image", label: "Image" },
          { type: "string", name: "category", label: "Category" },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
        ],
      },
    ],
  },
  {
    name: "cabinetos_page",
    label: "Cabinetos page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "cabinetos" },
    ui: pageUi,
    fields: [
      { type: "string", name: "eyebrow", label: "Eyebrow" },
      { type: "string", name: "title", label: "Title", isTitle: true, required: true },
      { type: "string", name: "titleAccent", label: "Title accent" },
      { type: "string", name: "subtitle", label: "Subtitle", ui: { component: "textarea" } },
      { type: "string", name: "primaryCtaLabel", label: "Primary CTA" },
      { type: "string", name: "secondaryCtaLabel", label: "Secondary CTA" },
      { type: "image", name: "heroImage", label: "Hero / demo screenshot" },
      { type: "string", name: "heroImageAlt", label: "Hero image alt text" },
      { type: "string", name: "mockupEmoji", label: "Mockup emoji (fallback)" },
      { type: "string", name: "mockupPlaceholder", label: "Mockup placeholder (fallback)" },
      { type: "string", name: "featuresSectionTitle", label: "Features section title" },
      { type: "string", name: "featuresSectionTitleAccent", label: "Features section title accent" },
      { type: "string", name: "featuresSectionSubtitle", label: "Features section subtitle" },
      {
        type: "object",
        name: "features",
        label: "Features",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Title" },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          { type: "string", name: "icon", label: "Icon" },
        ],
      },
      {
        type: "object",
        name: "beforeAfterItems",
        label: "Before / after comparison items",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "image", name: "beforeImage", label: "Before image" },
          { type: "image", name: "afterImage", label: "After image" },
          { type: "string", name: "beforeAlt", label: "Before image alt" },
          { type: "string", name: "afterAlt", label: "After image alt" },
        ],
      },
      { type: "string", name: "withoutTitle", label: "Without column title" },
      { type: "string", name: "withoutBullets", label: "Without column bullets", list: true },
      { type: "string", name: "withTitle", label: "With column title" },
      { type: "string", name: "withBullets", label: "With column bullets", list: true },
      { type: "string", name: "faqSectionTitle", label: "FAQ section title" },
      { type: "string", name: "faqSectionTitleAccent", label: "FAQ section title accent" },
      {
        type: "object",
        name: "faq",
        label: "FAQ",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "question", label: "Question", ui: { component: "textarea" } },
          { type: "string", name: "answer", label: "Answer", ui: { component: "textarea" } },
        ],
      },
      { type: "string", name: "bottomCtaTitle", label: "Bottom CTA title" },
      { type: "string", name: "bottomCtaTitleAccent", label: "Bottom CTA title accent" },
      { type: "string", name: "bottomCtaSubtitle", label: "Bottom CTA subtitle", ui: { component: "textarea" } },
      { type: "string", name: "bottomCtaButtonLabel", label: "Bottom CTA button" },
    ],
  },
  {
    name: "sketchup_page",
    label: "SketchUp page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "sketchup" },
    ui: pageUi,
    fields: [
      { type: "string", name: "heroTitle", label: "Hero title", isTitle: true, required: true },
      { type: "string", name: "heroTitleAccent", label: "Hero title accent" },
      { type: "string", name: "heroParagraphs", label: "Hero paragraphs", list: true, ui: { component: "textarea" } },
      { type: "string", name: "subtitle", label: "Subtitle (unused)", ui: { component: "textarea" } },
      { type: "image", name: "heroImage", label: "Hero image" },
      { type: "string", name: "heroImageAlt", label: "Hero image alt" },
      { type: "string", name: "heroImageCaption", label: "Hero image caption" },
      { type: "string", name: "benefitsSectionTitle", label: "Benefits section title" },
      { type: "string", name: "benefitsSectionTitleAccent", label: "Benefits section title accent" },
      {
        type: "object",
        name: "benefits",
        label: "Benefits",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Title" },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          { type: "string", name: "icon", label: "Icon" },
        ],
      },
      { type: "string", name: "comparisonTitle", label: "Comparison title" },
      { type: "string", name: "comparisonTitleAccent", label: "Comparison title accent" },
      { type: "string", name: "comparisonSubtitle", label: "Comparison subtitle", ui: { component: "textarea" } },
      { type: "image", name: "comparisonModelImage", label: "Comparison model image" },
      { type: "string", name: "comparisonModelAlt", label: "Comparison model alt" },
      { type: "string", name: "comparisonModelLabel", label: "Comparison model label" },
      { type: "image", name: "comparisonBuildImage", label: "Comparison build image" },
      { type: "string", name: "comparisonBuildAlt", label: "Comparison build alt" },
      { type: "string", name: "comparisonBuildLabel", label: "Comparison build label" },
      { type: "string", name: "plansTitle", label: "Plans: title" },
      { type: "string", name: "plansIntro", label: "Plans: intro", ui: { component: "textarea" } },
      {
        type: "object",
        name: "plansBundle",
        label: "Plans: bundle (leave the link empty to hide)",
        fields: [
          { type: "string", name: "label", label: "Label, e.g. All 4 plans" },
          { type: "string", name: "price", label: "Price, e.g. £12.99" },
          { type: "string", name: "url", label: "Payhip bundle link" },
          { type: "string", name: "note", label: "Small note" },
        ],
      },
      { type: "string", name: "learnKicker", label: "Learn: small label" },
      { type: "string", name: "learnTitle", label: "Learn: title" },
      { type: "string", name: "learnBody", label: "Learn: text", ui: { component: "textarea" } },
      { type: "string", name: "learnPoints", label: "Learn: what you'll learn", list: true },
      {
        type: "object",
        name: "learnImages",
        label: "Learn: screenshots",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "image", name: "src", label: "Screenshot" },
          { type: "string", name: "caption", label: "Caption" },
          { type: "string", name: "alt", label: "Description for screen readers" },
          { type: "number", name: "w", label: "Width in px" },
          { type: "number", name: "h", label: "Height in px" },
        ],
      },
      { type: "string", name: "learnButtonLabel", label: "Learn: button text" },
      { type: "string", name: "learnButtonUrl", label: "Learn: button link (mailto now, Skool later)" },
      { type: "string", name: "learnNote", label: "Learn: note under the button" },
      { type: "string", name: "ctaTitle", label: "CTA title" },
      { type: "string", name: "ctaSubtitle", label: "CTA subtitle", ui: { component: "textarea" } },
      { type: "string", name: "ctaButtonLabel", label: "CTA button" },
    ],
  },
  {
    name: "tools_page",
    label: "Tools page",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "tools" },
    ui: pageUi,
    fields: [
      { type: "string", name: "metaTitle", label: "Meta title", isTitle: true, required: true },
      { type: "string", name: "metaDescription", label: "Meta description", ui: { component: "textarea" } },
      { type: "string", name: "title", label: "Page title" },
      { type: "string", name: "titleAccent", label: "Page title accent" },
      { type: "string", name: "intro", label: "Intro", ui: { component: "textarea" } },
      { type: "string", name: "disclosure", label: "Affiliate disclosure", ui: { component: "textarea" } },
      {
        type: "object",
        name: "categories",
        label: "Categories",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "name", label: "Name" },
          { type: "string", name: "icon", label: "Icon" },
          {
            type: "object",
            name: "tools",
            label: "Tools",
            list: true,
            ui: listItemUi,
            fields: [
              { type: "string", name: "name", label: "Name" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
              { type: "string", name: "url", label: "URL" },
              { type: "image", name: "image", label: "Image" },
              { type: "string", name: "price", label: "Price band" },
            ],
          },
        ],
      },
      { type: "string", name: "footerCtaTitle", label: "Footer CTA title" },
      { type: "string", name: "footerCtaTitleAccent", label: "Footer CTA title accent" },
      { type: "string", name: "footerCtaSubtitle", label: "Footer CTA subtitle", ui: { component: "textarea" } },
      { type: "string", name: "footerCtaButtonLabel", label: "Footer CTA button" },
    ],
  },
  {
    name: "ms_page",
    label: "Mini-site (/ms)",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "ms" },
    ui: pageUi,
    fields: [
      { type: "string", name: "metaTitle", label: "Meta title", isTitle: true, required: true },
      { type: "string", name: "metaDescription", label: "Meta description", ui: { component: "textarea" } },
      { type: "string", name: "title", label: "Profile title" },
      { type: "string", name: "subtitle", label: "Profile subtitle" },
      {
        type: "object",
        name: "links",
        label: "Links",
        list: true,
        ui: listItemUi,
        fields: [
          { type: "string", name: "label", label: "Label" },
          { type: "string", name: "subtitle", label: "Subtitle", ui: { component: "textarea" } },
          { type: "string", name: "url", label: "URL" },
          { type: "string", name: "icon", label: "Icon" },
          { type: "boolean", name: "highlight", label: "Highlight" },
        ],
      },
      { type: "string", name: "instagramUrl", label: "Instagram URL" },
      { type: "string", name: "tiktokUrl", label: "TikTok URL" },
      { type: "string", name: "facebookUrl", label: "Facebook URL" },
    ],
  },
  {
    name: "services_page",
    label: "Services",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "services" },
    ui: pageUi,
    fields: [
      { type: "string", name: "metaTitle", label: "Services page: meta title", isTitle: true, required: true },
      { type: "string", name: "metaDescription", label: "Services page: meta description", ui: { component: "textarea" } },
      { type: "string", name: "kicker", label: "Services page: small line above the title" },
      { type: "string", name: "title", label: "Services page: title" },
      { type: "string", name: "titleAccent", label: "Services page: title, last words (in blue)" },
      { type: "string", name: "lede", label: "Services page: intro", ui: { component: "textarea" } },
      { type: "string", name: "faqHeading", label: "Questions heading (on every service page)" },
      {
        type: "object", name: "services", label: "Services (one page each)", list: true,
        ui: { itemProps: (item: Record<string, unknown>) => ({ label: (typeof item?.name === "string" && item.name) || "Service" }) },
        fields: [
          { type: "string", name: "name", label: "Name (page title)", required: true },
          { type: "string", name: "slug", label: "Web address", description: "rafcarpentry.com/services/<this>. Lowercase words with dashes. Changing it breaks old links.", required: true },
          { type: "string", name: "titleAccent", label: "Title, last words (in blue)" },
          { type: "string", name: "summary", label: "One line for the Services page card" },
          { type: "string", name: "intro", label: "Intro", ui: { component: "textarea" } },
          { type: "string", name: "metaTitle", label: "Google title" },
          { type: "string", name: "metaDescription", label: "Google description", ui: { component: "textarea" } },
          { type: "image", name: "image", label: "Card photo (optional)", description: "Empty uses the newest job's photo." },
          {
            type: "object", name: "photos", label: "Loose photos", list: true,
            description: "Usually filled from the Mac folder \"0 Services\". The first one is the card photo.",
            ui: { itemProps: (item: Record<string, unknown>) => ({ label: (typeof item?.alt === "string" && item.alt) || "Photo" }) },
            fields: [
              { type: "image", name: "src", label: "Photo", required: true },
              { type: "string", name: "alt", label: "What it shows" },
              { type: "number", name: "w", label: "Width in px (filled in automatically)" },
              { type: "number", name: "h", label: "Height in px (filled in automatically)" },
            ],
          },
          { type: "string", name: "matchTypes", label: "Show jobs of these types", list: true, description: "Exactly as the job's Type, e.g. Fitted wardrobes" },
          { type: "string", name: "matchTags", label: "...or with these tags", list: true, description: "Exactly as the job's tags, e.g. IKEA PAX" },
          {
            type: "object", name: "points", label: "Four points under the title", list: true, ui: listItemUi,
            fields: [
              { type: "string", name: "title", label: "Point", required: true },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object", name: "faq", label: "Questions", list: true, ui: listItemUi,
            fields: [
              { type: "string", name: "question", label: "Question", required: true },
              { type: "string", name: "answer", label: "Answer", ui: { component: "textarea" } },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "reviews_page",
    label: "Reviews",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "reviews" },
    ui: pageUi,
    fields: [
      { type: "string", name: "heading", label: "Heading", isTitle: true, required: true },
      { type: "string", name: "intro", label: "Line under the heading" },
      { type: "string", name: "googleRating", label: "Google rating (e.g. 4.8)", description: "Copy it from your Google Business Profile when it changes." },
      { type: "string", name: "googleCount", label: "Number of Google reviews (e.g. 27)" },
      {
        type: "object", name: "reviews", label: "Reviews", list: true, ui: listItemUi,
        description: "Real reviews only, copied from Google. The first three show on the home page; on a job page, reviews about that job come first.",
        fields: [
          { type: "string", name: "name", label: "Customer first name", required: true },
          { type: "string", name: "area", label: "Area (e.g. Highbury)" },
          { type: "string", name: "text", label: "Review", ui: { component: "textarea" }, required: true },
          { type: "number", name: "stars", label: "Stars (1 to 5)" },
          { type: "string", name: "job", label: "Job page (optional)", description: "The end of the job's address, e.g. floating-walnut-desk-highbury" },
        ],
      },
    ],
  },
  {
    name: "how_it_works_page",
    label: "Plan your project (How it works page)",
    path: pagesPath,
    format: jsonFormat,
    match: { include: "how-it-works" },
    ui: pageUi,
    fields: [
      { type: "string", name: "metaTitle", label: "Meta title", isTitle: true, required: true },
      { type: "string", name: "metaDescription", label: "Meta description", ui: { component: "textarea" } },
      { type: "string", name: "kicker", label: "Small line above the title" },
      { type: "string", name: "title", label: "Title" },
      { type: "string", name: "titleAccent", label: "Title, last words (in blue)" },
      { type: "string", name: "lede", label: "Intro", ui: { component: "textarea" } },
      { type: "string", name: "needHeading", label: "What I need: heading" },
      { type: "string", name: "needIntro", label: "What I need: intro", ui: { component: "textarea" } },
      {
        type: "object", name: "need", label: "What I need from you", list: true, ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Item", required: true },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          {
            type: "string", name: "sketch", label: "Little drawing",
            description: "The small sketch beside this item. Leave empty to show the number instead.",
            options: [
              { value: "photos", label: "Phone photo of the wall" },
              { value: "sizes", label: "Unit with width and height" },
              { value: "uses", label: "Open wardrobe (what goes inside)" },
              { value: "look", label: "Pinned pictures with a heart" },
              { value: "details", label: "House and parking sign" },
              { value: "budget", label: "Calendar and pound coin" },
            ],
          },
        ],
      },
      { type: "string", name: "getHeading", label: "What you get: heading" },
      {
        type: "object", name: "get", label: "What you get from me", list: true, ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Item", required: true },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          {
            type: "string", name: "sketch", label: "Little drawing",
            description: "The small sketch beside this item. Leave empty to show a tick instead.",
            options: [
              { value: "reply", label: "Message and 24h clock" },
              { value: "visit", label: "Quote sheet and tape measure" },
              { value: "drawing", label: "Signed 3D drawing" },
              { value: "board", label: "18 mm board" },
              { value: "fitted", label: "Wardrobe scribed to the wall" },
            ],
          },
        ],
      },
      { type: "string", name: "materialsHeading", label: "Materials: heading" },
      { type: "string", name: "materialsIntro", label: "Materials: intro", ui: { component: "textarea" } },
      {
        type: "object", name: "materials", label: "Materials", list: true, ui: listItemUi,
        fields: [
          { type: "string", name: "name", label: "Material", required: true },
          { type: "string", name: "cost", label: "Cost compared (£ to ££££)" },
          { type: "string", name: "bestFor", label: "Best for" },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          { type: "image", name: "image", label: "Photo" },
          { type: "string", name: "imageAlt", label: "Photo description" },
          { type: "string", name: "link", label: "Job page link (e.g. /portfolio/vanity-unit-bowes-park)" },
        ],
      },
      { type: "string", name: "costNote", label: "Note under the materials", ui: { component: "textarea" } },
      { type: "string", name: "finishesHeading", label: "Finishes: heading" },
      {
        type: "object", name: "finishes", label: "Finishes and details", list: true, ui: listItemUi,
        fields: [
          { type: "string", name: "title", label: "Title", required: true },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
        ],
      },
      { type: "string", name: "briefHeading", label: "Brief: heading" },
      { type: "string", name: "briefIntro", label: "Brief: intro", ui: { component: "textarea" } },
      { type: "string", name: "briefWhat", label: "Brief choices: What is it?", list: true },
      { type: "string", name: "briefRoom", label: "Brief choices: Which room?", list: true },
      { type: "string", name: "briefUses", label: "Brief choices: What is it for?", list: true },
      { type: "string", name: "briefMaterial", label: "Brief choices: Material", list: true },
      { type: "string", name: "briefFinish", label: "Brief choices: Finish", list: true },
      { type: "string", name: "briefTiming", label: "Brief choices: When?", list: true },
      { type: "string", name: "briefBudget", label: "Brief choices: Rough budget", list: true },
      { type: "string", name: "briefParking", label: "Brief choices: Parking", list: true },
      { type: "string", name: "briefPhotoTips", label: "Brief: photos to send (tips)", list: true },
      { type: "string", name: "faqHeading", label: "Questions: heading" },
      {
        type: "object", name: "faq", label: "Questions", list: true, ui: listItemUi,
        fields: [
          { type: "string", name: "question", label: "Question", required: true },
          { type: "string", name: "answer", label: "Answer", ui: { component: "textarea" } },
        ],
      },
      { type: "string", name: "ctaHeading", label: "Bottom: heading" },
      { type: "string", name: "ctaText", label: "Bottom: text", ui: { component: "textarea" } },
    ],
  },
];
